# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import time
from typing import Any
import json
import os
import re
import shutil
import subprocess
import sys


def get_version(ext_version_script: str) -> str:
    """Retrieves the extension version."""
    try:
        result = subprocess.run(
            [sys.executable, ext_version_script],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except Exception as e:
        print(f"Error getting extension version: {e}", file=sys.stderr)
        return "666"  # Fallback


def parse_ruby_config(path: str) -> dict[str, str]:
    """Parses a Ruby config file for Google Ads."""
    data = {}
    patterns = {
        "developer_token": r"c\.developer_token\s*=\s*['\"](.*?)['\"]",
        "client_id": r"c\.client_id\s*=\s*['\"](.*?)['\"]",
        "client_secret": r"c\.client_secret\s*=\s*['\"](.*?)['\"]",
        "refresh_token": r"c\.refresh_token\s*=\s*['\"](.*?)['\"]",
        "login_customer_id": r"c\.login_customer_id\s*=\s*['\"](.*?)['\"]",
        "json_key_file_path": r"c\.json_key_file_path\s*=\s*['\"](.*?)['\"]",
        "impersonated_email": r"c\.impersonated_email\s*=\s*['\"](.*?)['\"]",
    }
    try:
        with open(path, "r") as f:
            content = f.read()
            for key, pattern in patterns.items():
                match = re.search(pattern, content)
                if match:
                    data[key] = match.group(1)
    except Exception as e:
        print(f"Error parsing Ruby config: {e}", file=sys.stderr)
    return data


def parse_ini_config(path: str) -> dict[str, str]:
    """Parses a PHP INI config file for Google Ads."""
    data = {}
    patterns = {
        "developer_token": r"developerToken\s*=\s*(.*)$",
        "client_id": r"clientId\s*=\s*(.*)$",
        "client_secret": r"clientSecret\s*=\s*(.*)$",
        "refresh_token": r"refreshToken\s*=\s*(.*)$",
        "login_customer_id": r"loginCustomerId\s*=\s*(.*)$",
        "json_key_file_path": r"jsonKeyFilePath\s*=\s*(.*)$",
        "impersonated_email": r"impersonatedEmail\s*=\s*(.*)$",
    }
    try:
        with open(path, "r") as f:
            for line in f:
                for key, pattern in patterns.items():
                    match = re.search(pattern, line)
                    if match:
                        data[key] = match.group(1).strip(" \"'\n")
    except Exception as e:
        print(f"Error parsing INI config: {e}", file=sys.stderr)
    return data


def parse_properties_config(path: str) -> dict[str, str]:
    """Parses a Java properties config file for Google Ads."""
    data = {}
    mapping = {
        "api.googleads.developerToken": "developer_token",
        "api.googleads.clientId": "client_id",
        "api.googleads.clientSecret": "client_secret",
        "api.googleads.refreshToken": "refresh_token",
        "api.googleads.loginCustomerId": "login_customer_id",
        "api.googleads.oAuth2SecretsJsonPath": "json_key_file_path",
        "api.googleads.oAuth2PrnEmail": "impersonated_email",
    }
    try:
        with open(path, "r") as f:
            for line in f:
                if "=" in line:
                    k, v = line.split("=", 1)
                    k = k.strip()
                    if k in mapping:
                        data[mapping[k]] = v.strip()
    except Exception as e:
        print(f"Error parsing properties config: {e}", file=sys.stderr)
    return data


def write_yaml_config(data: dict[str, str], target_path: str, version: str | None = None) -> bool:
    """Writes a standard Google Ads YAML config."""
    try:
        service_account = "json_key_file_path" in data
        with open(target_path, "w") as f:
            f.write("# Generated by Antigravity Assistant\n")
            f.write(
                "developer_token: "
                + data.get("developer_token", "INSERT_DEVELOPER_TOKEN_HERE")
                + "\n"
            )

            if service_account:
                f.write(
                    "json_key_file_path: " + data["json_key_file_path"] + "\n"
                )
                if "impersonated_email" in data:
                    f.write(
                        "impersonated_email: "
                        + data["impersonated_email"]
                        + "\n"
                    )
            else:
                f.write(
                    "client_id: "
                    + data.get("client_id", "INSERT_CLIENT_ID_HERE")
                    + "\n"
                )
                f.write(
                    "client_secret: "
                    + data.get("client_secret", "INSERT_CLIENT_SECRET_HERE")
                    + "\n"
                )
                f.write(
                    "refresh_token: "
                    + data.get("refresh_token", "INSERT_REFRESH_TOKEN_HERE")
                    + "\n"
                )

            if "login_customer_id" in data:
                f.write("login_customer_id: " + data["login_customer_id"] + "\n")
            f.write("use_proto_plus: True\n")
            if version:
                f.write(f"ads_assistant: {version}\n")
        return True
    except Exception as e:
        print(f"Error writing YAML config: {e}", file=sys.stderr)
        return False


def copy_and_append_version(home_config: str, target_config: str, version: str, lang: str = "YAML") -> bool:
    """Copies a configuration file and appends the extension version to it idiomatically."""
    if not os.path.exists(home_config):
        return False

    try:
        shutil.copy2(home_config, target_config)
        with open(target_config, "a") as f:
            if lang == "YAML":
                line = f"ads_assistant: {version}"
            elif lang == "PHP":
                line = f'ads_assistant = "{version}"'
            elif lang == "Ruby":
                line = f"ENV['ADS_ASSISTANT'] = '{version}'"
            elif lang == "Java":
                line = f"api.googleads.ads_assistant={version}"
            else:
                line = f"ads_assistant: {version}"

            f.write(f"\n{line}\n")
        return True
    except Exception as e:
        print(f"Error copying config {home_config}: {e}", file=sys.stderr)
        return False


def finish_hook(target_path: str, version: str) -> None:
    """Outputs the hook's JSON response with steps to inject into the conversation."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "../.."))

    # Construct the JSON output required by Antigravity PreInvocationHookResult.
    # It supports only injectSteps which can contain userMessage, ephemeralMessage, or toolCall.
    # We inject an ephemeral message to inform the agent about configuration and venv path.
    message_content = (
        "StartSession initialized. "
        f"Virtual environment is located at {project_root}/.venv. "
        f"Google Ads configuration file is written to {target_path}. "
        f"Extension version is {version}. "
        "You MUST use this virtual environment for linting, validation, and execution. "
        f"When running Python scripts, use the python interpreter at {project_root}/.venv/bin/python3. "
        f"Always run Google Ads client scripts with the environment variable GOOGLE_ADS_CONFIGURATION_FILE_PATH={target_path} set."
    )

    output = {
        "injectSteps": [
            {
                "ephemeralMessage": message_content
            }
        ]
    }
    # Output to stdout
    print(json.dumps(output))





def create_virtual_env(project_root: str) -> None:
    """Creates a virtual environment in the project root if it doesn't exist or is outdated."""
    venv_dir = os.path.join(project_root, ".venv")
    venv_python = os.path.join(venv_dir, "bin", "python3")

    should_create = True

    if os.path.exists(venv_dir):
        print("Virtual environment already exists. Checking Python version...", file=sys.stderr)
        try:
            # Get version from virtual env Python
            import ast

            result = subprocess.run(
                [venv_python, "-c", "import sys; print(list(sys.version_info[:3]))"],
                capture_output=True,
                text=True,
                check=True
            )
            venv_version = tuple(ast.literal_eval(result.stdout.strip()))
            available_version = sys.version_info[:3]

            print(f"Virtual environment Python version: {venv_version}", file=sys.stderr)
            print(f"Available Python version: {available_version}", file=sys.stderr)

            if available_version > venv_version:
                print("Virtual environment Python version is outdated. Recreating...", file=sys.stderr)
                shutil.rmtree(venv_dir)
            else:
                print("Virtual environment is up to date.", file=sys.stderr)
                should_create = False
        except Exception as e:
            print(f"Error checking virtual environment Python version (it might be broken): {e}", file=sys.stderr)
            print("Deleting broken virtual environment and recreating...", file=sys.stderr)
            try:
                shutil.rmtree(venv_dir)
            except Exception as del_err:
                print(f"Failed to delete virtual environment directory: {del_err}", file=sys.stderr)

    if should_create:
        print(f"Creating virtual environment in {venv_dir}...", file=sys.stderr)
        try:
            # Use sys.executable to ensure we use the same Python version
            subprocess.run([sys.executable, "-m", "venv", venv_dir], check=True)
            print("Virtual environment created successfully.", file=sys.stderr)

            # Upgrade pip
            print(f"Upgrading pip in {venv_dir}...", file=sys.stderr)
            subprocess.run(
                [venv_python, "-m", "pip", "install", "-q", "--upgrade", "pip"],
                check=True,
                stdout=subprocess.DEVNULL,
            )
            print("pip upgraded successfully.", file=sys.stderr)

            # Install google-ads and ruff
            print(f"Installing google-ads and ruff into {venv_dir}...", file=sys.stderr)
            subprocess.run(
                [venv_python, "-m", "pip", "install", "-q", "google-ads", "ruff", "pytest"],
                check=True,
                stdout=subprocess.DEVNULL,
            )
            print("google-ads installed successfully.", file=sys.stderr)
        except Exception as e:
            print(f"Failed to create virtual environment: {e}", file=sys.stderr)


class TimestampedStream:
    """Custom stream wrapper that prefixes written lines with standard datetime stamps."""
    def __init__(self, original_stream: Any) -> None:
        self.original_stream = original_stream
        self.at_start_of_line = True

    def write(self, message: str) -> None:
        if not message:
            return
        lines = message.split('\n')
        for i, line in enumerate(lines):
            if i > 0:
                self.original_stream.write('\n')
                self.at_start_of_line = True
            if line:
                if self.at_start_of_line:
                    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S,%f')[:-3]
                    self.original_stream.write(f"{timestamp} [INFO] ")
                    self.at_start_of_line = False
                self.original_stream.write(line)

    def flush(self) -> None:
        self.original_stream.flush()


def main() -> None:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    log_path = os.path.join(script_dir, "hook_debug.log")
    log_file = open(log_path, "a", buffering=1)  # buffering=1 for line-buffered writes
    import sys

    sys.stderr = TimestampedStream(log_file)

    try:
        print("DEBUG: Executing configure_environment.py...", file=sys.stderr)
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.abspath(os.path.join(script_dir, "../.."))

        # Create isolated virtual environment
        create_virtual_env(project_root)
        config_dir = os.path.join(project_root, "config")

        # Delete cached API version if it's older than 19 hours
        api_version_path = os.path.join(config_dir, "api_version.txt")
        if os.path.exists(api_version_path):
            mtime = os.path.getmtime(api_version_path)
            now = time.time()
            if now - mtime > 68400:  # 19 hours * 3600 seconds/hour
                try:
                    os.remove(api_version_path)
                    print("DEBUG: Deleted stale api_version.txt (older than 19 hours)", file=sys.stderr)
                except Exception as e:
                    print(f"Error removing stale api_version.txt: {e}", file=sys.stderr)

        ext_version_script = os.path.join(
            project_root,
            ".agents/skills/ext_version/scripts/get_extension_version.py",
        )

        os.makedirs(config_dir, exist_ok=True)
        version = get_version(ext_version_script)

        home_dir = os.path.expanduser("~")
        print(f"DEBUG: home_dir={home_dir}", file=sys.stderr)
        python_home = os.path.join(home_dir, "google-ads.yaml")
        print(
            f"DEBUG: python_home={python_home} (exists={os.path.exists(python_home)})",
            file=sys.stderr,
        )
        python_target = os.path.join(config_dir, "google-ads.yaml")
        print(f"DEBUG: python_target={python_target}", file=sys.stderr)

        # 1. Try Python YAML first
        if copy_and_append_version(
            python_home, python_target, version, lang="YAML"
        ):
            print("Configured Python config directly", file=sys.stderr)
        else:
            # 2. Try fallbacks
            fallbacks = [
                ("PHP", "google_ads_php.ini", parse_ini_config),
                ("Ruby", "google_ads_config.rb", parse_ruby_config),
                ("Java", "ads.properties", parse_properties_config),
            ]

            found_fallback = False
            for lang, filename, parser in fallbacks:
                home_path = os.path.join(home_dir, filename)
                target_path = os.path.join(config_dir, filename)

                if os.path.exists(home_path):
                    print(
                        f"Found {lang} config at {home_path}. Copying and creating a Python YAML fallback...",
                        file=sys.stderr,
                    )

                    # Copy original file to config dir and append version
                    copy_and_append_version(
                        home_path, target_path, version, lang=lang
                    )

                    # Parse the original file and create a new google-ads.yaml in the config dir
                    data = parser(home_path)
                    if write_yaml_config(data, python_target, version=version):
                        print(
                            f"Successfully generated {python_target} from {lang} config",
                            file=sys.stderr,
                        )
                        found_fallback = True
                        break

            if not found_fallback:
                print(
                    "Error: No Google Ads configuration found in home directory. Please create ~/google-ads.yaml.",
                    file=sys.stderr,
                )
                sys.exit(1)

        # 3. Complete Hook Execution
        finish_hook(python_target, version)
    except Exception as e:
        import traceback

        print(f"CRITICAL HOOK ERROR: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
