import os
import shutil
import subprocess
import json
import sys
import re

def get_version(ext_version_script):
    """Retrieves the extension version."""
    try:
        result = subprocess.run(
            [sys.executable, ext_version_script],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except Exception as e:
        print(f"Error getting extension version: {e}", file=sys.stderr)
        return "2.0.0" # Fallback

def parse_ruby_config(path):
    """Parses a Ruby config file for Google Ads."""
    data = {}
    patterns = {
        "developer_token": r"c\.developer_token\s*=\s*['\"](.*?)['\"]",
        "client_id": r"c\.client_id\s*=\s*['\"](.*?)['\"]",
        "client_secret": r"c\.client_secret\s*=\s*['\"](.*?)['\"]",
        "refresh_token": r"c\.refresh_token\s*=\s*['\"](.*?)['\"]",
        "login_customer_id": r"c\.login_customer_id\s*=\s*['\"](.*?)['\"]",
    }
    try:
        with open(path, "r") as f:
            content = f.read()
            for key, pattern in patterns.items():
                match = re.search(pattern, content)
                if match:
                    data[key] = match.group(1)
    except Exception as e:
        print(f"Error parsing Ruby config: {e}", file=sys.stderr)
    return data

def parse_ini_config(path):
    """Parses a PHP INI config file for Google Ads."""
    data = {}
    patterns = {
        "developer_token": r"developer_token\s*=\s*['\"]?(.*?)['\"]?\s*$",
        "client_id": r"client_id\s*=\s*['\"]?(.*?)['\"]?\s*$",
        "client_secret": r"client_secret\s*=\s*['\"]?(.*?)['\"]?\s*$",
        "refresh_token": r"refresh_token\s*=\s*['\"]?(.*?)['\"]?\s*$",
        "login_customer_id": r"login_customer_id\s*=\s*['\"]?(.*?)['\"]?\s*$",
    }
    try:
        with open(path, "r") as f:
            for line in f:
                for key, pattern in patterns.items():
                    match = re.search(pattern, line)
                    if match:
                        data[key] = match.group(1)
    except Exception as e:
        print(f"Error parsing INI config: {e}", file=sys.stderr)
    return data

def parse_properties_config(path):
    """Parses a Java properties config file for Google Ads."""
    data = {}
    mapping = {
        "api.googleads.developerToken": "developer_token",
        "api.googleads.clientId": "client_id",
        "api.googleads.clientSecret": "client_secret",
        "api.googleads.refreshToken": "refresh_token",
        "api.googleads.loginCustomerId": "login_customer_id",
    }
    try:
        with open(path, "r") as f:
            for line in f:
                if "=" in line:
                    k, v = line.split("=", 1)
                    k = k.strip()
                    if k in mapping:
                        data[mapping[k]] = v.strip()
    except Exception as e:
        print(f"Error parsing properties config: {e}", file=sys.stderr)
    return data

def write_yaml_config(data, target_path, version):
    """Writes a standard Google Ads YAML config."""
    try:
        with open(target_path, "w") as f:
            f.write("# Generated by Gemini CLI Assistant\n")
            f.write("developer_token: " + data.get("developer_token", "INSERT_DEVELOPER_TOKEN_HERE") + "\n")
            f.write("client_id: " + data.get("client_id", "INSERT_CLIENT_ID_HERE") + "\n")
            f.write("client_secret: " + data.get("client_secret", "INSERT_CLIENT_SECRET_HERE") + "\n")
            f.write("refresh_token: " + data.get("refresh_token", "INSERT_REFRESH_TOKEN_HERE") + "\n")
            if "login_customer_id" in data:
                f.write("login_customer_id: " + data["login_customer_id"] + "\n")
            f.write("use_proto_plus: True\n")
            f.write(f"gaada: \"{version}\"\n")
        return True
    except Exception as e:
        print(f"Error writing YAML config: {e}", file=sys.stderr)
        return False

def configure_language(lang_name, home_config, target_config, version, is_python=False):
    """Copies and versions a specific language configuration."""
    if not os.path.exists(home_config):
        return False

    try:
        shutil.copy2(home_config, target_config)
        with open(target_config, "a", encoding="utf-8") as f:
            sep = ":" if is_python else "="
            f.write(f"\ngaada {sep} \"{version}\"\n")
        return True
    except Exception as e:
        print(f"Error configuring {lang_name}: {e}", file=sys.stderr)
        return False

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, "../.."))
    config_dir = os.path.join(project_root, "config")
    ext_version_script = os.path.join(project_root, ".gemini/skills/ext_version/scripts/get_extension_version.py")
    
    os.makedirs(config_dir, exist_ok=True)
    version = get_version(ext_version_script)

    home_dir = os.path.expanduser("~")
    python_home = os.path.join(home_dir, "google-ads.yaml")
    python_target = os.path.join(config_dir, "google-ads.yaml")

    # 1. Try Python YAML first
    if configure_language("Python", python_home, python_target, version, is_python=True):
        print("Configured Python using ~/google-ads.yaml")
    else:
        # 2. Try fallbacks
        fallbacks = [
            ("PHP", "google_ads_php.ini", parse_ini_config),
            ("Ruby", "google_ads_config.rb", parse_ruby_config),
            ("Java", "ads.properties", parse_properties_config),
        ]
        
        found_fallback = False
        for lang, filename, parser in fallbacks:
            path = os.path.join(home_dir, filename)
            if os.path.exists(path):
                print(f"Found {lang} config at {path}. Converting to YAML...")
                data = parser(path)
                if write_yaml_config(data, python_target, version):
                    print(f"Successfully converted {lang} config to {python_target}")
                    found_fallback = True
                    break
        
        if not found_fallback:
            print("Warning: No Google Ads configuration found in home directory.", file=sys.stderr)

    # 3. Configure other languages if requested by workspace context
    settings_path = os.path.join(project_root, ".gemini/settings.json")
    if os.path.exists(settings_path):
        try:
            with open(settings_path, "r") as f:
                settings = json.load(f)
            include_dirs = settings.get("context", {}).get("includeDirectories", [])
        except:
            include_dirs = []

        languages = [
            {"id": "google-ads-php", "name": "PHP", "filename": "google_ads_php.ini", "home": os.path.join(home_dir, "google_ads_php.ini")},
            {"id": "google-ads-ruby", "name": "Ruby", "filename": "google_ads_config.rb", "home": os.path.join(home_dir, "google_ads_config.rb")},
        ]

        for lang in languages:
            if any(lang["id"] in d for d in include_dirs):
                target = os.path.join(config_dir, lang["filename"])
                configure_language(lang["name"], lang["home"], target, version)

if __name__ == "__main__":
    main()
